Request feats skills
Skalord88/ded_card pull request #27
Opened 2023-05-20 06:47 UTC by Skalord88

2023-05-26 23:26 UTC, JustynaKolenda requested changes

2023-05-26 23:26 UTC, JustynaKolenda commented on api/src/main/java/pl/kolendateam/dadcard/armorClass/dto/armorClassDTO.java
> +
czy nazwa pliku nie powinna być z dużej litery, bo ostatnio przy odpalaniu z któryms plikiem był problem bo nazwa była z małej a importowałeś z dużej

2023-05-28 19:47 UTC, Skalord88 commented on api/src/main/java/pl/kolendateam/dadcard/armorClass/dto/armorClassDTO.java
> +
powinno być ok teraz

2023-06-05 14:00 UTC, JustynaKolenda approved these changes

2023-06-12 06:32 UTC, merged