Request class feats
Skalord88/ded_card pull request #28
Opened 2023-05-28 19:38 UTC by Skalord88

2023-05-28 20:19 UTC, JustynaKolenda requested changes

2023-05-28 20:19 UTC, JustynaKolenda commented on api/src/main/java/pl/kolendateam/dadcard/armorClass/dto/armorClassDTO.java
ponawiam pytanie czy plik nie powinien być nazwany z dużej litery?

2023-05-28 20:19 UTC, JustynaKolenda commented on api/src/main/java/pl/kolendateam/dadcard/armorClass/dto/armorClassDTO.java
zwłaszcza, że np. plik AtackDto masz z dużej zapisany

2023-05-28 20:19 UTC, JustynaKolenda commented on api/src/main/java/pl/kolendateam/dadcard/race/entity/Race.java
> -    @NonNull
a armor nie powinno mieć jednak jakiejś wartości ? chociażby 0 ?

2023-06-01 17:17 UTC, Skalord88 commented on api/src/main/java/pl/kolendateam/dadcard/armorClass/dto/armorClassDTO.java
poprawiłem!

2023-06-01 17:21 UTC, Skalord88 commented on api/src/main/java/pl/kolendateam/dadcard/race/entity/Race.java
> -    @NonNull
nie, bo nie wszystkie klasy mają zapisane w pliku xml armor. Np ludzie nie mają bonusów do armora

2023-06-05 14:01 UTC, JustynaKolenda approved these changes

2023-06-12 07:02 UTC, merged