Request size skill
Skalord88/ded_card pull request #31
Opened 2023-06-01 18:14 UTC by Skalord88

2023-06-05 23:47 UTC, JustynaKolenda requested changes

2023-06-05 23:47 UTC, JustynaKolenda commented on api/src/main/java/pl/kolendateam/dadcard/characterCard/dto/CharacterDTO.java
> +        this.size = character.getSize().getSize();
i tu

2023-06-22 12:11 UTC, JustynaKolenda approved these changes

2023-06-24 12:21 UTC, dkolenda approved these changes

2023-07-12 20:34 UTC, merged