Feats dupplicate
Skalord88/ded_card pull request #36
Opened 2023-07-15 22:56 UTC by Skalord88

2023-07-17 22:17 UTC, JustynaKolenda approved these changes
Kawał dobrej roboty :)

2023-07-18 18:43 UTC, dkolenda requested changes

2023-07-18 18:43 UTC, dkolenda commented on api/src/main/java/pl/kolendateam/dadcard/characterCard/dto/CharacterDTO.java
> +<<<<<<< HEAD
zmergowales z konfliktem

2023-07-18 18:43 UTC, dkolenda commented on api/src/main/java/pl/kolendateam/dadcard/feats/dto/CharacterFeatsDTO.java
> +            case "Rage" ->
do enum lb stalych

2023-07-19 11:29 UTC, closed without merging

2023-07-19 11:30 UTC, Skalord88 commented
pull 37 jest poprawiony