Set class
Skalord88/ded_card pull request #42
Opened 2023-08-03 09:12 UTC by JustynaKolenda

2023-08-09 16:46 UTC, Skalord88 approved these changes

2023-08-19 11:22 UTC, dkolenda requested changes

2023-08-19 11:22 UTC, dkolenda commented on mobile/src/feature/characterDetails/CharacterDetails.tsx
> +console.log(item.classPcList)
console

2023-08-19 11:22 UTC, dkolenda commented on mobile/src/feature/class/Class.tsx
> +export const Class = ()=> {
nie nazywamy class Class CharacterClass sugeruje

2024-06-12 16:09 UTC, closed without merging